theme = "careercanvas"

[params]
  name = "Marco Gora"
  tagline = "Eat. Sleep. Architect. Repeat."
  hero_location = "Berlin, Germany"
  email = "marco.gora.de@gmail.com"
  profile_image = "/images/marco.jpg"
  description = ""
  author = "Marco Gora"

  # Social Media
  linkedin_url = "https://www.linkedin.com/in/marco-gora-8920502b1/"
  linkedin_text = "linkedin.com/in/marco-gora-8920502b1/"
  github_url = "https://github.com/m-gora"
  github_text = "github.com/m-gora"


  # Resume/CV
  resume_url_en = "/files/your-resume-en.pdf"  # Path to English resume
  resume_url_fr = "/files/your-resume-fr.pdf"  # Path to French resume (optional)
  resume_label = "Full Resume"

  # Social Icons
  [[params.social]]
    icon = "linkedin-in"
    url = "https://www.linkedin.com/in/marco-gora-8920502b1/"

  [[params.social]]
    icon = "github"
    url = "https://github.com/m-gora"

[params.pexels]
  # Image search queries for random background images
  # Customize this list to change the types of images that appear
  # The system will randomly select from these queries for each page loads
  queries = [
    # "galaxy", "nebula", "planet", "astronomy",
    # "solar system", "black hole", "constellation", "meteor",
    # "comet", "asteroid", "space station", "satellite",
    # "structural long span bridges", "structural skycrapers", "astronomy nasa pictures",
    "universe solar systems nasa pictures", "structural long span bridges",
    "nebula nasa pictures",
  ]